Install with pip:

`$ pip install pyvis`

Let's add **[Pandas](https://pandas.pydata.org/)** - a data manipulation package in Python for tabular data. 

[Python pandas Tutorial: The Ultimate Guide for Beginners](https://www.datacamp.com/tutorial/pandas)

Installing pandas is straightforward; just use the pip install command in your terminal:

`$ pip install pandas`

In [1]:
# step 1
import pandas as pd
from pyvis.network import Network

In [2]:
# step 2
# Loading the data as well as displaying rows
data = pd.read_csv("data/game-of-thrones-battles.csv")
data.head()

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,...,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,...,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN

In [3]:
# step 3
# Displaying information about the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                38 non-null     object
 1   year                38 non-null     int64
 2   battle_number       38 non-null     int64
 3   attacker_king       36 non-null     object
 4   defender_king       35 non-null     object
 5   attacker_1          38 non-null     object
 6   attacker_2          10 non-null     object
 7   attacker_3          3 non-null      object
 8   attacker_4          2 non-null      object
 9   defender_1          37 non-null     object
 10  defender_2          2 non-null      object
 11  defender_3          0 non-null      float64
 12  defender_4          0 non-null      float64
 13  attacker_outcome    37 non-null     object
 14  battle_type         37 non-null     object
 15  major_death         37 non-null     float64
 16  major_capture       37 non-null     float64
 17  attacker_size       24 non-null     float64
 18  defender_size       19 non-null     float64
 19  attacker_commander  37 non-null     object
 20  defender_commander  28 non-null     object
 21  summer              37 non-null     float64
 22  location            37 non-null     object
 23  region              38 non-null     object
 24  note                5 non-null      object
dtypes: float64(7), int64(2), object(16)
memory usage: 7.6+ KB

In [4]:
# step 4
# Select required columns: name, attacker_king, defender_king, attacker_size, defender_size.
battles_df=data.loc[:,['name','attacker_king','defender_king','attacker_size','defender_size']]
battles_df.head()

,name,attacker_king,defender_king,attacker_size,defender_size
0,Battle of the Golden Tooth,Joffrey/Tommen Baratheon,Robb Stark,15000.0,4000.0
1,Battle at the Mummer's Ford,Joffrey/Tommen Baratheon,Robb Stark,NaN,120.0
2,Battle of Riverrun,Joffrey/Tommen Baratheon,Robb Stark,15000.0,10000.0
3,Battle of the Green Fork,Robb Stark,Joffrey/Tommen Baratheon,18000.0,20000.0
4,Battle of the Whispering Wood,Robb Stark,Joffrey/Tommen Baratheon,1875.0,6000.0

In [5]:
# step 5
# Displaying information about the new dataframe
battles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           38 non-null     object
 1   attacker_king  36 non-null     object
 2   defender_king  35 non-null     object
 3   attacker_size  24 non-null     float64
 4   defender_size  19 non-null     float64
dtypes: float64(2), object(3)
memory usage: 1.6+ KB

In [6]:
# step 6
# remove rows with any missing values (NaN)
battles_df_cleaned=battles_df.dropna()
battles_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 37
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           16 non-null     object
 1   attacker_king  16 non-null     object
 2   defender_king  16 non-null     object
 3   attacker_size  16 non-null     float64
 4   defender_size  16 non-null     float64
dtypes: float64(2), object(3)
memory usage: 768.0+ bytes

In [7]:
# step 6.5
battles_df_cleaned.head(3)

,name,attacker_king,defender_king,attacker_size,defender_size
0,Battle of the Golden Tooth,Joffrey/Tommen Baratheon,Robb Stark,15000.0,4000.0
2,Battle of Riverrun,Joffrey/Tommen Baratheon,Robb Stark,15000.0,10000.0
3,Battle of the Green Fork,Robb Stark,Joffrey/Tommen Baratheon,18000.0,20000.0

In [8]:
# step 7
# Output names of attacking kings (without repetitions):
print(f"Attacking kings: {battles_df_cleaned.attacker_king.unique()}")

Attacking kings: ['Joffrey/Tommen Baratheon' 'Robb Stark' 'Stannis Baratheon']

In [9]:
# step 8
# Output names of defending kings (without repetitions):
print(f"Defending kings: {battles_df_cleaned.defender_king.unique()}")

Defending kings: ['Robb Stark' 'Joffrey/Tommen Baratheon' 'Balon/Euron Greyjoy'
 'Renly Baratheon' 'Mance Rayder']

In [10]:
# step 9
# Instantiate a Network object from pyvis.network.
net5kings = Network(
heading="Task1. Building Interactive Network of battles of the War of 5",
bgcolor ="#242020",
font_color = "white",
height = "1000px",
width = "100%",
directed = True, # we have directed graph
notebook = True,
cdn_resources = "remote"
 )   # do this

In [11]:
# step 10
# Define nodes - the list of unique names of all kings
kingList = set(battles_df_cleaned.attacker_king.unique()) | set(battles_df_cleaned.defender_king.unique())
print(f"Kings list (nodes names): {kingList}")

Kings list (nodes names): {'Joffrey/Tommen Baratheon', 'Balon/Euron Greyjoy', 'Renly Baratheon', 'Robb Stark', 'Mance Rayder', 'Stannis Baratheon'}

In [12]:
# step 11
# Add nodes to the graph. Output them via netkings.nodes after that.
net5kings.add_nodes(kingList)
print(f"Nodes of net5kings properties: {net5kings.nodes}")

Nodes of net5kings properties: [{'color': '#97c2fc', 'id': 'Joffrey/Tommen Baratheon', 'label': 'Joffrey/Tommen Baratheon', 'shape': 'dot', 'font': {'color': 'white'}}, {'color': '#97c2fc', 'id': 'Balon/Euron Greyjoy', 'label': 'Balon/Euron Greyjoy', 'shape': 'dot', 'font': {'color': 'white'}}, {'color': '#97c2fc', 'id': 'Renly Baratheon', 'label': 'Renly Baratheon', 'shape': 'dot', 'font': {'color': 'white'}}, {'color': '#97c2fc', 'id': 'Robb Stark', 'label': 'Robb Stark', 'shape': 'dot', 'font': {'color': 'white'}}, {'color': '#97c2fc', 'id': 'Mance Rayder', 'label': 'Mance Rayder', 'shape': 'dot', 'font': {'color': 'white'}}, {'color': '#97c2fc', 'id': 'Stannis Baratheon', 'label': 'Stannis Baratheon', 'shape': 'dot', 'font': {'color': 'white'}}]

In [13]:
# step 12
# Define Potential edges are defined as (king1_name, king2_name) pairs 
# taken from the attacker_king and defender_king columns 
# of battles_df_cleaned, 
# where king1_name is the attacking king
# king2_name is the defending king.
potential_edges = battles_df_cleaned[['attacker_king', 'defender_king']].values.tolist()
print("Potential Edges of net5kings:")
for edge in potential_edges:
    print(edge)

Potential Edges of net5kings:
['Joffrey/Tommen Baratheon', 'Robb Stark']
['Joffrey/Tommen Baratheon', 'Robb Stark']
['Robb Stark', 'Joffrey/Tommen Baratheon']
['Robb Stark', 'Joffrey/Tommen Baratheon']
['Robb Stark', 'Joffrey/Tommen Baratheon']
['Robb Stark', 'Balon/Euron Greyjoy']
['Joffrey/Tommen Baratheon', 'Robb Stark']
['Robb Stark', 'Joffrey/Tommen Baratheon']
['Stannis Baratheon', 'Renly Baratheon']
['Joffrey/Tommen Baratheon', 'Robb Stark']
['Robb Stark', 'Joffrey/Tommen Baratheon']
['Stannis Baratheon', 'Joffrey/Tommen Baratheon']
['Joffrey/Tommen Baratheon', 'Robb Stark']
['Stannis Baratheon', 'Mance Rayder']
['Stannis Baratheon', 'Balon/Euron Greyjoy']
['Stannis Baratheon', 'Joffrey/Tommen Baratheon']

In [14]:
# step 13
# Create the list (set) of real edges (without repetitions) based on potential edges defined earlier.

real_edges = set()
for edge in potential_edges:
    real_edges.add(tuple(edge))

print("Real (unique) directed Edges of net5kings:")
for edge in real_edges:
    print(edge)

Real (unique) directed Edges of net5kings:
('Joffrey/Tommen Baratheon', 'Robb Stark')
('Stannis Baratheon', 'Mance Rayder')
('Stannis Baratheon', 'Joffrey/Tommen Baratheon')
('Stannis Baratheon', 'Balon/Euron Greyjoy')
('Robb Stark', 'Balon/Euron Greyjoy')
('Stannis Baratheon', 'Renly Baratheon')
('Robb Stark', 'Joffrey/Tommen Baratheon')

In [15]:
# step 14
# Calculate edges weights as the total number of battles between king 1 and king 2, where( king 1, king 2)- an edge.
battle_count_edges = battles_df_cleaned.groupby(['attacker_king', 'defender_king']).agg(count = ('name', 'count'))
print(battle_count_edges)

                                                   count
attacker_king            defender_king
Joffrey/Tommen Baratheon Robb Stark                    5
Robb Stark               Balon/Euron Greyjoy           1
                         Joffrey/Tommen Baratheon      5
Stannis Baratheon        Balon/Euron Greyjoy           1
                         Joffrey/Tommen Baratheon      2
                         Mance Rayder                  1
                         Renly Baratheon               1

In [16]:
# step 15
# Define the titles for edges by using data from battles_df_cleaned about battles' name, attacker_size, and defender_size columns.
def join_battle(x):
    return ', '.join(x)
battle_title_edges = battles_df_cleaned.groupby(['attacker_king', 'defender_king']).agg(title = ('name', join_battle))
print(battle_title_edges)

                                                                                               title
attacker_king            defender_king
Joffrey/Tommen Baratheon Robb Stark                Battle of the Golden Tooth, Battle of Riverrun...
Robb Stark               Balon/Euron Greyjoy                              Battle of Torrhen's Square
                         Joffrey/Tommen Baratheon  Battle of the Green Fork, Battle of the Whispe...
Stannis Baratheon        Balon/Euron Greyjoy                              Retaking of Deepwood Motte
                         Joffrey/Tommen Baratheon      Battle of the Blackwater, Siege of Winterfell
                         Mance Rayder                                         Battle of Castle Black
                         Renly Baratheon                                        Siege of Storm's End

In [17]:
# step 16
# Assign the weight of each edge and output them as follows:
full_edges = (battles_df_cleaned.groupby(['attacker_king', 'defender_king']).agg
              (  n_battles = ('name', 'count'),
                title = ('name', join_battle))
            ).reset_index()
edges_weights = full_edges['n_battles'].tolist()
for index, row in full_edges.iterrows():
    print(f"Attacking king: {row['attacker_king']}, Defending king: {row['defender_king']},  N of battles: {row['n_battles']}, Titles: {row['title']}")
print(f"edges_weights: {edges_weights}")

Attacking king: Joffrey/Tommen Baratheon, Defending king: Robb Stark,  N of battles: 5, Titles: Battle of the Golden Tooth, Battle of Riverrun, Sack of Winterfell, Battle of the Fords, The Red Wedding
Attacking king: Robb Stark, Defending king: Balon/Euron Greyjoy,  N of battles: 1, Titles: Battle of Torrhen's Square
Attacking king: Robb Stark, Defending king: Joffrey/Tommen Baratheon,  N of battles: 5, Titles: Battle of the Green Fork, Battle of the Whispering Wood, Battle of the Camps, Battle of Oxcross, Sack of Harrenhal
Attacking king: Stannis Baratheon, Defending king: Balon/Euron Greyjoy,  N of battles: 1, Titles: Retaking of Deepwood Motte
Attacking king: Stannis Baratheon, Defending king: Joffrey/Tommen Baratheon,  N of battles: 2, Titles: Battle of the Blackwater, Siege of Winterfell
Attacking king: Stannis Baratheon, Defending king: Mance Rayder,  N of battles: 1, Titles: Battle of Castle Black
Attacking king: Stannis Baratheon, Defending king: Renly Baratheon,  N of battles: 1, Titles: Siege of Storm's End
edges_weights: [5, 1, 5, 1, 2, 1, 1]

In [18]:
# step 17
# Add edges with their weights to the net5kings (via .add_edge) and output results as follows:
for index, row in full_edges.iterrows():
    print(f"The edge from {row['attacker_king']} to {row['defender_king']} with weight {row['n_battles']}, title: '{row['title']}'")
    net5kings.add_edge(row['attacker_king'], row['defender_king'],value=row['n_battles'], title=row['title'])

The edge from Joffrey/Tommen Baratheon to Robb Stark with weight 5, title: 'Battle of the Golden Tooth, Battle of Riverrun, Sack of Winterfell, Battle of the Fords, The Red Wedding'
The edge from Robb Stark to Balon/Euron Greyjoy with weight 1, title: 'Battle of Torrhen's Square'
The edge from Robb Stark to Joffrey/Tommen Baratheon with weight 5, title: 'Battle of the Green Fork, Battle of the Whispering Wood, Battle of the Camps, Battle of Oxcross, Sack of Harrenhal'
The edge from Stannis Baratheon to Balon/Euron Greyjoy with weight 1, title: 'Retaking of Deepwood Motte'
The edge from Stannis Baratheon to Joffrey/Tommen Baratheon with weight 2, title: 'Battle of the Blackwater, Siege of Winterfell'
The edge from Stannis Baratheon to Mance Rayder with weight 1, title: 'Battle of Castle Black'
The edge from Stannis Baratheon to Renly Baratheon with weight 1, title: 'Siege of Storm's End'

In [19]:
# step 18
net5kings.edges

[{'value': 5,
  'title': 'Battle of the Golden Tooth, Battle of Riverrun, Sack of Winterfell, Battle of the Fords, The Red Wedding',
  'from': 'Joffrey/Tommen Baratheon',
  'to': 'Robb Stark',
  'arrows': 'to'},
 {'value': 1,
  'title': "Battle of Torrhen's Square",
  'from': 'Robb Stark',
  'to': 'Balon/Euron Greyjoy',
  'arrows': 'to'},
 {'value': 5,
  'title': 'Battle of the Green Fork, Battle of the Whispering Wood, Battle of the Camps, Battle of Oxcross, Sack of Harrenhal',
  'from': 'Robb Stark',
  'to': 'Joffrey/Tommen Baratheon',
  'arrows': 'to'},
 {'value': 1,
  'title': 'Retaking of Deepwood Motte',
  'from': 'Stannis Baratheon',
  'to': 'Balon/Euron Greyjoy',
  'arrows': 'to'},
 {'value': 2,
  'title': 'Battle of the Blackwater, Siege of Winterfell',
  'from': 'Stannis Baratheon',
  'to': 'Joffrey/Tommen Baratheon',
  'arrows': 'to'},
 {'value': 1,
  'title': 'Battle of Castle Black',
  'from': 'Stannis Baratheon',
  'to': 'Mance Rayder',
  'arrows': 'to'},
 {'value': 1,
  'title': "Siege of Storm's End",
  'from': 'Stannis Baratheon',
  'to': 'Renly Baratheon',
  'arrows': 'to'}]

In [20]:
# step 19
# Assign the value of node (to scale the node's size) as the N of kings (N+ 1) that this king (a node)
# has attacked in battles. Hint: use .get_adj_list () (enemies_map) to retrieve an adjacency list
# representation of the directed graph
enemies_map = net5kings.get_adj_list()
enemies_map

{'Joffrey/Tommen Baratheon': {'Robb Stark'},
 'Balon/Euron Greyjoy': set(),
 'Renly Baratheon': set(),
 'Robb Stark': {'Balon/Euron Greyjoy', 'Joffrey/Tommen Baratheon'},
 'Mance Rayder': set(),
 'Stannis Baratheon': {'Balon/Euron Greyjoy',
  'Joffrey/Tommen Baratheon',
  'Mance Rayder',
  'Renly Baratheon'}}

In [21]:
# step 20
# By using enemies_map (defined earlie) output the following
for king, enemies in enemies_map.items():
    N = len(set(enemies)) + 1
    print(f"King: {king} has attacked: {enemies}, N of enemies: {N - 1}, node's value: {N}")

King: Joffrey/Tommen Baratheon has attacked: {'Robb Stark'}, N of enemies: 1, node's value: 2
King: Balon/Euron Greyjoy has attacked: set(), N of enemies: 0, node's value: 1
King: Renly Baratheon has attacked: set(), N of enemies: 0, node's value: 1
King: Robb Stark has attacked: {'Joffrey/Tommen Baratheon', 'Balon/Euron Greyjoy'}, N of enemies: 2, node's value: 3
King: Mance Rayder has attacked: set(), N of enemies: 0, node's value: 1
King: Stannis Baratheon has attacked: {'Joffrey/Tommen Baratheon', 'Balon/Euron Greyjoy', 'Mance Rayder', 'Renly Baratheon'}, N of enemies: 4, node's value: 5

In [22]:
# step 20
# Use the following color dictionary to assign a color to a node according to its value (specified earlier):
nodeColors={
    0:"blue",
    1: "green",
    2: "orange",
    3: "purple",
    4: "gold",
    5:"red"
}

In [23]:
# step 21
# Assign values and color to nodes. Output results via net5kings.nodes

for node in net5kings.nodes:
    king_name = node['id']
    enemies = enemies_map.get(king_name, [])
    N = len(set(enemies)) + 1
    node['value'] = N
    node['color'] = nodeColors[node['value']]
net5kings.nodes

[{'color': 'orange',
  'id': 'Joffrey/Tommen Baratheon',
  'label': 'Joffrey/Tommen Baratheon',
  'shape': 'dot',
  'font': {'color': 'white'},
  'value': 2},
 {'color': 'green',
  'id': 'Balon/Euron Greyjoy',
  'label': 'Balon/Euron Greyjoy',
  'shape': 'dot',
  'font': {'color': 'white'},
  'value': 1},
 {'color': 'green',
  'id': 'Renly Baratheon',
  'label': 'Renly Baratheon',
  'shape': 'dot',
  'font': {'color': 'white'},
  'value': 1},
 {'color': 'purple',
  'id': 'Robb Stark',
  'label': 'Robb Stark',
  'shape': 'dot',
  'font': {'color': 'white'},
  'value': 3},
 {'color': 'green',
  'id': 'Mance Rayder',
  'label': 'Mance Rayder',
  'shape': 'dot',
  'font': {'color': 'white'},
  'value': 1},
 {'color': 'red',
  'id': 'Stannis Baratheon',
  'label': 'Stannis Baratheon',
  'shape': 'dot',
  'font': {'color': 'white'},
  'value': 5}]

In [24]:
net5kings.show("Jehad's Lab1-task1-net5kings.html", notebook=False)

Jehad's Lab1-task1-net5kings.html